#!/bin/bash

  ###########
  # bashLED #
  ###########

BLVER="1.0"
PNAME="BashLED"

if [[ $1 == "" ]]
then
  echo -e "\e[0;94musage\e[0m: \e[0;92m$0 \e[0medit\e[0;94m/\e[0mplay\e[0;94m/\e[0minit playlistName"
  echo -e "  \e[0;94medit\e[0m: Open playlist in a text editor.       "
  echo -e "  \e[0;94mplay\e[0m: Play the playlist.                    "
  echo -e "  \e[0;94minit\e[0m: Create a BashLED playlist.            "
  echo -e "                                                           "
  echo -e "\e[0;92m$PNAME \e[0;92m$BLVER \e[0mby \e[0;93mfgclue\e[0m. email: \e[0;93mlost\e[0m@\e[0;93mbiitle.nl\e[0m"
fi

if [[ $1 == "init" ]]
then
  if [[ $2 == "" ]]
  then
    echo "Playlist name not provided."
  fi
  echo "Creating playlist..."
  mkdir -p ~/.local/share/bashled
  mkdir -p ~/.local/share/bashled/$2
  mkdir -p ~/.local/share/bashled/$2/files
  touch ~/.local/share/bashled/$2/playlist
  echo "# BashLED Playlist file" >> ~/.local/share/bashled/$2/playlist
  echo "# How to add files:" >> ~/.local/share/bashled/$2/playlist
  echo "# Add a line that starts with mpv, then the file name." >> ~/.local/share/bashled/$2/playlist
  echo "# Example: mpv file.mp4" >> ~/.local/share/bashled/$2/playlist
  echo "Playlist created at ~/.local/share/bashled/$2."
fi
if [[ $1 == "edit" ]]
then
  if [[ $2 == "" ]]
  then
    echo "Error: You need to enter a playlist name."
    exit
  fi
  if [[ -e "~/.local/share/bashled/$2/" ]]
  then
    $EDITOR ~/.local/share/bashled/$2
  else
    echo "Error: No playlist called $2 exists."
  fi
fi
if [[ $1 == "play" ]]
then
  if [[ $2 == "" ]]
  then
    echo "Error: You need to enter a playlist name."
    exit
  fi
  if [[ -e "~/.local/share/bashled/$2/" ]]
  then
    cd ~/.local/bashled/$2/
    chmod a+xrw playlist
    cd files
    ../playlist
  else
    echo "Error: No playlist called $2 exists."
  fi
fi
